export const SKILLS = {
  ALL: [
    ["HTML"],
    ["CSS"],
    ["SASS"],
    ["Java", "Script"],
    ["Type", "Script"],
    ["React", ".js"],
    ["Redux"],
    ["Next", ".js"],
    ["Node", ".js"],
    ["Express", ".js"],
    ["Mongo", "DB"],
    ["Fire", "base"],
  ],
  AQUA_TRACK: [
    ["HTML"],
    ["CSS"],
    ["Java", "Script"],
    ["React", ".js"],
    ["Redux"],
    ["Node", ".js"],
    ["Express", ".js"],
    ["Mongo", "DB"],
  ],
  Nanny_Services: [
    ["HTML"],
    ["CSS"],
    ["SASS"],
    ["Type", "Script"],
    ["React", ".js"],
    ["Redux"],
    ["Fire", "base"],
  ],
  CONTACTS: [
    ["HTML"],
    ["CSS"],
    ["Java", "Script"],
    ["React", ".js"],
    ["Redux"],
  ],
  BATTLE_SHIP: [["HTML"], ["CSS"], ["Type", "Script"], ["React", ".js"]],
  TRAVEL_TRACKS: [
    ["HTML"],
    ["CSS"],
    ["Java", "Script"],
    ["React", ".js"],
    ["Redux"],
  ],
};
